### ISSUE TITLE
Yg perlu diperbaiki di halaman registration

### ISSUE THREAD

**Issue by Ariska138** [Naufalirsd/Portal-Siswa-By-Naufalirsd#1]
- [x] Ketika buka halaman utama, jangan tampil halaman nextjs. sebaiknya diarahkan ke halaman login atau ke dashboard jika sudah login.
- [x] Ketika melakukan registrasi, terjadi error ketika menekan tombol buat akun
- [x] untuk bagian code
```
<a href="/login" className={styles["signin"]}>
                            Masuk
                        </a>
```                     
seharusnya:
```
<Link href="/login" className={styles['signin']}>
              Masuk
            </Link>
```
jangan lupa tambahkan
`import Link from 'next/link';`
- [x] pada halaman registrasi. untuk mengirimkan data ke api, menggunakan data useState dari form yg diinputkan. kesalahan pada code berikut:
`const { nis, password, name } = req.body;`
- [x] biar halaman registration tidak auto reload ketika mengirimkan data. tambahkan code di event button click pada tombol buat akun
`e.preventDefault();`

**Comment by Naufalirsd** [comment]
sudah selesai
1. ketika halaman utama langsung ke login ![contoh](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/ebbe3671-5483-4344-b9b3-b6516d2d3415)
2. memperbaiki login ![contoh2](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/292540e4-e072-4683-906d-e9115f423aaa)
