### ISSUE TITLE
Tidak ada info di Dashboard

### ISSUE THREAD

**Issue by Ariska138** [Naufalirsd/Portal-Siswa-By-Naufalirsd#2]
Tampilan dasboard setelah login
![image](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/1137972/de7ae83b-a30c-46cb-8326-7b16b132b2e5)

- [x] silakan tampilkan nama dengan role (admin/siswa/santri)
- [x] silakan tampilan list siswa/santri ketika login sebagai admin

**Comment by Naufalirsd** [comment]
@Ariska138 sudah selesai mas
![contoh9](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/0fca08c3-5151-41ce-bbf8-e3ef183effd5)

**Comment by Ariska138** [comment]
sip
