### ISSUE TITLE
Belum menerapkan login menggunakan Session dan cookies secara bersamaan

### ISSUE THREAD

**Issue by Ariska138** [Naufalirsd/Portal-Siswa-By-Naufalirsd#3]
Tampilan halaman login
![image](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/1137972/e7e7f96b-1c5f-44b4-94e6-701abf805cd1)

- [x] belum terdapat menu opsi apakah disimpan tokennya atau tidak.
- [x] ketika tidak menyimpan token, lalu tutup tab maka user langsung otomatis logout
- [x] ketika menyimpan token, lalu tutup tab maka user masih keadaan login

**Comment by Naufalirsd** [comment]
@Ariska138 kayaknya sudah deh mas
![contoh4](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/b9d1988e-b6f4-4677-a890-3f9474f8c5fc)

**Comment by Ariska138** [comment]
sip
