### ISSUE TITLE
Menemukan masalah, masih tetap bisa membuka dasboard ketika sudah logout

### ISSUE THREAD

**Issue by Ariska138** [Naufalirsd/Portal-Siswa-By-Naufalirsd#4]
- [x] tambahkan kondisi ketika token tidak tersedia. maka diarahkan ke halaman login

contoh solusi, ketika myToken kosong. diarahkan ke halaman login
```
if (myToken) {
         ...
        } else {
          router.push('/login');
        }
```

**Comment by Naufalirsd** [comment]
@Ariska138 sudah mas
![contoh6](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/bfd570ee-a778-4f32-b719-ff957c5b2c8f)

**Comment by Ariska138** [comment]
oke
