### ISSUE TITLE
masalah: List Users untuk Tidak muncul

### ISSUE THREAD

**Issue by Ariska138** [Naufalirsd/Portal-Siswa-By-Naufalirsd#6]
ketika buka log di browser. muncul error 404
![image](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/1137972/024851b1-cef2-4fda-8bfd-59cd784eae96)
bahwa url/path tidak valid
ketika dibuka ternyata ada typo pada penamaan API
![image](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/1137972/d82991bb-5666-4864-8803-ab615f1010a3)
bukan listUsers.js tetapi liatUsers.js

silakan diperbaiki

- [x] mengubah nama liatUsers.js menjadi listUsers.js

**Comment by Naufalirsd** [comment]
@Ariska138 sudah muncul tapi belum kelihatan
![contoh7](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/88fd1ec5-5d40-4478-b5dc-ebb68db5e92a)

**Comment by Ariska138** [comment]
sip
