### ISSUE TITLE
Masalah Minor: (Optional) Tampilan tidak support Dark Mode

### ISSUE THREAD

**Issue by Ariska138** [Naufalirsd/Portal-Siswa-By-Naufalirsd#7]
![image](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/1137972/c573b0ef-88d0-4015-bb15-fe0513a5ecb3)

- [x] silakan perbaiki cssnya (masalah sama yg di hadapi sama danesh)

**Comment by Naufalirsd** [comment]
@Ariska138 sudah mas
![contoh8](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/9be6c4a3-6cd0-4e72-9057-0da434657ced)

**Comment by Ariska138** [comment]
mantap
