### ISSUE TITLE
Belum Ada feature Admin: Feature Mengelola Tugas (API)

### ISSUE THREAD

**Issue by Ariska138** [Naufalirsd/Portal-Siswa-By-Naufalirsd#8]
Feature2 Admin dalam mengelola Tugas

- [x] Membuat Tugas
- [x] Lihat seluruh tugas
- [x] Lihat tugas by id
- [x] edit tugas by id
- [x] delete tugas by id

**Comment by Naufalirsd** [comment]
@Ariska138 ini yang membuat tugas
![create-new-task1](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/4e10fe71-f5ad-4d97-b5cd-abcc08a764b0)

**Comment by Naufalirsd** [comment]
@Ariska138 ini yang melihat semua tugas
![get-all-tasks](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/04b6f9b3-c6d1-4304-90c1-6f7f81b9ea2c)

**Comment by Naufalirsd** [comment]
@Ariska138 ini melihat tugas berdasarkan id
![get-task-by-id](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/e10a696e-b884-4420-84dc-2002b20d46d1)

**Comment by Naufalirsd** [comment]
@Ariska138 ini edit task berdasarkan id
![edit-task-by-id1](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/20b9b29b-0837-4d86-b883-3733808c2343)

**Comment by Naufalirsd** [comment]
@Ariska138 ini yang delete tugas
![delete-task-by-id1](https://github.com/Naufalirsd/Portal-Siswa-By-Naufalirsd/assets/114051484/1101ea9e-37f6-4743-98cf-ed661be6940f)

**Comment by Ariska138** [comment]
mantap
